- hosts: localhost
  vars:
    username: nuurek
    home: /home/{{ username }}
  tasks:
  - name: Install required dependencies
    apt:
      pkg:
      - dbus-x11
      - libfuse2
      - python3-psutil
      - curl
  
  - name: Install git
    apt: name=git

  - name: Configure git
    copy:
      src: configs/common/git/.gitconfig
      dest: "~/.gitconfig"
    become: true
    become_user: "{{ username }}"

  - name: Install Guake
    apt: name=guake

  - name: Check if Guake config is updated
    shell: if [[ "`dconf dump /apps/guake/`" == "`cat configs/common/guake/guake.dconf`" ]]; then echo "true"; else echo "false"; fi
    args:
      executable: /bin/bash
    register: guake_config
    changed_when: guake_config.stdout == 'false'

  - name: Configure Guake
    when: guake_config.changed
    shell: cat configs/common/guake/guake.dconf | dconf load /apps/guake/

  - name: Install Visual Studio Code
    community.general.snap:
      name: code
      classic: true

  - name: Check if Google Chrome is installed
    command: which google-chrome
    register: google_chrome
    changed_when: google_chrome.rc != 0

  - name: Install Google Chrome
    when: google_chrome.changed
    apt:
      deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

  - name: Set Google Chrome as default web browser
    when: google_chrome.changed
    command: xdg-settings set default-web-browser google-chrome.desktop

  - name: Install PyCharm Professional Edition
    community.general.snap:
      name: pycharm-professional
      classic: true

  - name: Synchronize JetBrains configs
    synchronize:
      src: secrets/JetBrains/
      dest: "{{ home }}/.config/JetBrains/"
    become: true
    become_user: "{{ username }}"

  - name: Install Spotify
    community.general.snap:
      name: spotify

  - name: Set favorite apps
    community.general.dconf:
      key: '/org/gnome/shell/favorite-apps'
      value: "['org.gnome.Nautilus.desktop', 'google-chrome.desktop', 'rambox_rambox.desktop', 'code_code.desktop', 'spotify_spotify.desktop']"
    become: true
    become_user: "{{ username }}"

  - name: Set MIME Applications
    copy:
      src: configs/common/gnome/mimeapps.list
      dest: "~/.config/mimeapps.list"
    become: true
    become_user: "{{ username }}"
